Repository hmcts/em-hrs-ingestor, pull requests merged in 2021-08, with the labels that each got.

#171 Nojira set logging to info for parser and use vault for hrs container name
  Jenkinsfile_CNP
  src/main/resources/logback-test.xml
  src/test/java/uk/gov/hmcts/reform/em/hrs/ingestor/parse/FilenameParserWithFullDataExtractTest.java
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-171

#191 EM-4007: fix cve vulnerability
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-191

#192 set jakarta el version to 4.0.1
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-192

#198 Suppressed medium vulnerability
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-198

#193 gradle upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-193

#204 EM-4024: fix terraform version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-204
