Repository hmcts/em-hrs-ingestor, pull requests merged in 2022-09, with the labels that each got.

#395 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-395

#396 Updated renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-396

#399 Added in dependabot config
  .github/dependabot.yml
  .github/stale.yml
  renovate.json
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-399

#415 depenabot upgrades
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-415

#422 Em-4587 upgrade java17
  Dockerfile
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/config/AzureStorageConfiguration.java
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-422

#438 bump .terraform-version
  infrastructure/.terraform-version
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-ingestor-pr-438

#441 EM-4620 use spring configmap
  build.gradle
  charts/em-hrs-ingestor/Chart.yaml
  charts/em-hrs-ingestor/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-441

#444 process last 2 days
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-444
