Repository hmcts/em-hrs-ingestor, pull requests merged in 2022-03, with the labels that each got.

#318 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-318

#324 remove swaggerfox
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-324

#325 EM-4302 upgrade spring boot
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-325

#327 clean up dependency-management
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-327

#328 dependency-management-cleanup
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-328

#326 EM-4304 use jitpack versions
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-326

#288 add logs and wait when hrs-api is busy
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/service/DefaultIngestorService.java
Labels: stale, ns:em, prd:em, rel:em-hrs-ingestor-pr-288

#336 revert config map change
  build.gradle
  charts/em-hrs-ingestor/Chart.yaml
  charts/em-hrs-ingestor/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-336

#341 use config map
  build.gradle
  charts/em-hrs-ingestor/Chart.yaml
  charts/em-hrs-ingestor/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-341

#347 Update dependabot.yml
  .github/dependabot.yml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-347

#350 Fix CVE-2020-36518
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-350

#353 Updated azurerm & terraform version
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-353

#356 Remove unneeded deployment namespace var
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-356
