Repository hmcts/em-hrs-ingestor, pull requests merged in 2022-05, with the labels that each got.

#375 Updated config for Renovate Bot
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-375

#378 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-378

#384 Fix CVE-2022-29885
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-384

#385 Revert "Fix CVE-2022-29885"
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-385
