Repository hmcts/em-hrs-ingestor, pull requests merged in 2023-10, with the labels that each got.

#782 Suppress CVE-2023-4586
  config/owasp/suppressions.xml
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-782

#794 EM-5616 avoid CVE-2023-5072-vulnerability
  build.gradle
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-794

#801 EM-5505 reduce logs
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/config/AzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/listener/IngestWhenApplicationReadyListener.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/service/DefaultIngestorService.java
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-801
