Repository hmcts/em-hrs-ingestor, pull requests merged in 2023-09, with the labels that each got.

#732 Resolve CVE-2023-41080
  build.gradle
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-732

#735 wrap try-catch cvp run
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/service/DefaultIngestorService.java
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-735

#744 Update Renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-744

#755 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-755

#757 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, add-or-update, ns:em, rel:em-hrs-ingestor-pr-757

#762 EM-5551 extend renovate
  .github/renovate.json
  config/owasp/suppressions.xml
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-762
