Repository hmcts/em-hrs-ingestor, pull requests merged in 2023-03, with the labels that each got.

#574 Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-574

#584 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-584

#587 Updated CVE list
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-587

#590 EM-5120 upgrade spring boot
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/ingestor/config/TestAzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/Application.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/listener/IngestWhenApplicationReadyListener.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/ingestor/model/CvpItem.java
  src/smokeTest/java/uk/gov/hmcts/reform/em/hrs/ingestor/smoke/SmokeTest.java
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-590

#597 Resolve CVE-2022-1471
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-597
