Repository hmcts/em-hrs-ingestor, pull requests merged in 2023-01, with the labels that each got.

#507 EM-4912-suppress-vulnerability
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-507

#510 EM-4912-suppress CVE-2022-41915
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-510

#517 Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-517

#522 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-522

#541 EM-5015 bump-hmcts.java
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-541

#543 EM-5019 fix-pipeline
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-hrs-ingestor-pr-543
