Repository hmcts/em-hrs-ingestor, pull requests merged in 2024-12, with the labels that each got.

#1160 move pitest versioning to plugin
  build.gradle
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-1160

#1168 Create SECURITY.md
  SECURITY.md
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-1168

#1169 EM-6346 junit5
  build.gradle
Labels: prd:em, ns:em, rel:em-hrs-ingestor-pr-1169
